# Aula 03 - Elementos de Álgebra Linear
Curso de Introdução à Inteligência Artificial \\
Universidade Federal de Itajubá \\
Prof. Rodrigo Lima

# Exercícios resolvidos

In [1]:
# Bibliotecas que serão usadas.

import numpy as np
from scipy import linalg

Considere as matrizes $A$, $B$ e $C$ dadas por:

$$
A = \left(\begin{array}{rr}
-2 & 0 \\
4 & -1 \\
5 & 8
\end{array}\right), \quad
B = \left(\begin{array}{rrr}
1 & 0 & -2 \\
3 & 2 & 6 \\
\end{array}\right), \quad
C = \left(\begin{array}{rr}
2 & 1 \\
0 & 5
\end{array}\right).
$$

a) Efetue as operações $AB$ e $AC - 2B^T$.

In [2]:
# Declarando as matrizes:

A = np.array([[-2, 0],[4, -1],[5, 8]])
B = np.array([[1, 0, -2],[3, 2, 6]])
C = np.array([[2, 1],[0, 5]])

In [3]:
# Efetuando o produto AB:

AB = np.dot(A,B)
print(AB)

[[ -2   0   4]
 [  1  -2 -14]
 [ 29  16  38]]


In [4]:
# Efetuando a operação AC - 2B^T:

M = np.dot(A,C) - 2*B.T
print(M)

[[-6 -8]
 [ 8 -5]
 [14 33]]


b) Calcule o determinante de $C$ e, com base no valor obtido, responda se $C$ admite inversa.

In [5]:
detC = linalg.det(C)
print(detC)

# C admite inversa pois o determinante é diferente de zero.

10.0


c) Calcule os autovalores e autovetores de $C$.

In [6]:
solucao = linalg.eig(C)
print(solucao)

# A saída do comando eig contém duas listas: 
# na primeira estão os autovalores (2 e 5 neste caso) e 
# na segunda lista estão os autovetores armazenados nas linhas de uma matriz.

(array([2.+0.j, 5.+0.j]), array([[1.        , 0.31622777],
       [0.        , 0.9486833 ]]))


d) Obtenha a decomposição em valores singulares de $C$.

In [7]:
U, Sigma, V = linalg.svd(C)

In [8]:
# os vetores ortogonais u_i estão armazenados nas colunas.
print(U)

[[ 0.22975292 -0.97324899]
 [ 0.97324899  0.22975292]]


In [9]:
# a saída do comando fornece apenas uma lista com os valores singulares encontrados.
print(Sigma)

[5.11667274 1.95439508]


In [10]:
# os vetores ortogonais v_i estão armazenados nas linhas.
print(V)

[[ 0.0898056   0.99595931]
 [-0.99595931  0.0898056 ]]


In [11]:
# Recuperando a matriz C a partir da decomposição encontrada.

print(np.dot(U,np.dot(np.diag(Sigma),V)))

[[ 2.00000000e+00  1.00000000e+00]
 [-5.55111512e-17  5.00000000e+00]]


#Faça você mesmo!

Resolva o exercício abaixo utilizando comandos específicos do Python.

Considere a matriz $A = \left(\begin{array}{rrr} 1 & 2 & -1 \\ 2 & 3 & -2 \\ 1 & -2 & 1\end{array}\right)$.

a) Calcule o determinante de $A$. \\
b) Efetue a operação $A^TA - A^Tb$, onde $b = \left(\begin{array}{r} 1 \\ 2 \\ -1\end{array}\right)$. \\
c) Calcule os autovalores e autovetores de $A$. \\
d) Obtenha a decomposição em valores singulares de $A$.

In [12]:
# Declare a matriz A aqui.
A = np.array([[1, 2, -1], [2, 3, -2], [1, -2, 1]])

In [13]:
# Resolução do item a)
linalg.det(A)

-2.0

In [14]:
# Resolução do item b)
np.dot(A.T, A) - np.dot(A.T, np.array([[1], [2], [-1]]))

array([[  2,   2,  -8],
       [ -4,   7, -20],
       [  2,  -4,  12]])

In [15]:
# Resolução do item c)
linalg.eig(A)

(array([-0.59773519+0.j,  0.6804492 +0.j,  4.91728599+0.j]),
 array([[ 0.18660067, -0.42967649, -0.49300944],
        [-0.55454905, -0.34797008, -0.81938524],
        [-0.81095964, -0.83324363,  0.29248849]]))

In [16]:
# Resolução do item d)
linalg.svd(A)

(array([[-0.48215734,  0.0804168 , -0.87238606],
        [-0.80508333,  0.35202402,  0.4774096 ],
        [ 0.3454926 ,  0.93253002, -0.10498874]]),
 array([5.05606031, 1.84122207, 0.21483824]),
 array([[-0.3454926 , -0.80508333,  0.48215734],
        [ 0.93253002, -0.35202402,  0.0804168 ],
        [-0.10498874, -0.4774096 , -0.87238606]]))